### ISSUE TITLE
Can't get this to work in 10.7.0-rc3

### ISSUE THREAD

**Issue by MaticBabnik** [jellyfin/jellyfin-plugin-anilist#1]
After I build and copy this into the plugins folder I get this output:
```
jellyfin    | [15:52:31] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly SQLitePCLRaw.nativelibrary, Version=2.0.4.976, Culture=neutral, PublicKeyToken=502ed628492ab262 from /config/plugins/Anilist/SQLitePCLRaw.nativelibrary.dll
jellyfin    | [15:52:31] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Microsoft.Extensions.DependencyModel, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 from /config/plugins/Anilist/Microsoft.Extensions.DependencyModel.dll
jellyfin    | [15:52:31] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Microsoft.Extensions.Logging, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 from /config/plugins/Anilist/Microsoft.Extensions.Logging.dll
jellyfin    | [15:52:31] [FTL] [1] Main: Error while starting server.
jellyfin    | System.BadImageFormatException: Bad IL format. The format of the file '/config/plugins/Anilist/runtimes/win-arm64/native/e_sqlite3.dll' is invalid.
jellyfin    |    at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
jellyfin    |    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
jellyfin    |    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
jellyfin    |    at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
jellyfin    |    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
jellyfin    |    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
jellyfin    |    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.Init()
jellyfin    |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin    | [15:52:31] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
jellyfin    | [15:52:31] [INF] [2] Main: Received a SIGTERM signal, shutting down
```
Running in docker on arch linux, the image is `jellyfin/jellyfin:10.7.0-rc3`

**Comment by SoulyZero** [comment]
#metoo have this problem

**Comment by SoulyZero** [comment]
i use arch

**Comment by oddstr13** [comment]
That error could mean a corrupted dll file.

Can you check if the version in the repo also throws this error on 10.7.0?
