### ISSUE TITLE
Possible 429 issue?

### ISSUE THREAD

**Issue by controlia-pb** [jellyfin/jellyfin-plugin-anilist#87]
Hello I have a large library of anime (roughly 1k entries) and i am doing a library scan, sometimes the plugin gets the info without any hassle, other times there's a problem. This is all there's to it in the log
```
[2024-12-24 12:53:14.025 +01:00] [ERR] Error in "AniList"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.AniList.Providers.AniList.AniListApi.Search_GetSeries_list(String title, CancellationToken cancellationToken)
   at Jellyfin.Plugin.AniList.Providers.AniList.AniListApi.Search_GetSeries(String title, CancellationToken cancellationToken)
   at Jellyfin.Plugin.AniList.Providers.AniList.AniListSeriesProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```
I can't pinpoint if it's a 429 response from anilist, but assuming that it works sometimes I guess that's what it is

**Comment by de-odex** [comment]
I think there is an issue as in my case, when i do a full library metadata replace, certain titles are in English (taken from TVDB) from what I assume is from AniList ratelimiting the plugin and the plugin silently failing

**Comment by sjorge** [comment]
I would assume this would fix the issue https://github.com/jellyfin/jellyfin-plugin-anilist/pull/79
